name: random_number
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.8.2
  path_provider: ^0.5.0+1
  carousel_slider: ^1.0.1
  sensors: ^0.4.0+1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #audio alphabet and number
    - assets/audio/alphabet/a.mp3
    - assets/audio/alphabet/b.mp3
    - assets/audio/alphabet/c.mp3
    - assets/audio/alphabet/d.mp3
    - assets/audio/alphabet/e.mp3
    - assets/audio/alphabet/f.mp3
    - assets/audio/alphabet/g.mp3
    - assets/audio/alphabet/h.mp3
    - assets/audio/alphabet/i.mp3
    - assets/audio/alphabet/j.mp3
    - assets/audio/alphabet/k.mp3
    - assets/audio/alphabet/l.mp3
    - assets/audio/alphabet/m.mp3
    - assets/audio/alphabet/n.mp3
    - assets/audio/alphabet/o.mp3
    - assets/audio/alphabet/p.mp3
    - assets/audio/alphabet/q.mp3
    - assets/audio/alphabet/r.mp3
    - assets/audio/alphabet/s.mp3
    - assets/audio/alphabet/u.mp3
    - assets/audio/alphabet/v.mp3
    - assets/audio/alphabet/w.mp3
    - assets/audio/alphabet/x.mp3
    - assets/audio/alphabet/y.mp3
    - assets/audio/alphabet/z.mp3
    - assets/audio/alphabet/t.mp3
    - assets/audio/alphabet/0.mp3
    - assets/audio/alphabet/1.mp3
    - assets/audio/alphabet/2.mp3
    - assets/audio/alphabet/3.mp3
    - assets/audio/alphabet/4.mp3
    - assets/audio/alphabet/5.mp3
    - assets/audio/alphabet/6.mp3
    - assets/audio/alphabet/7.mp3
    - assets/audio/alphabet/8.mp3
    - assets/audio/alphabet/9.mp3
    - assets/audio/alphabet/10.mp3
    #audio color
    - assets/audio/color/Black.mp3
    - assets/audio/color/Blue.mp3
    - assets/audio/color/Brown.mp3
    - assets/audio/color/Green.mp3
    - assets/audio/color/Lime.mp3
    - assets/audio/color/Orange.mp3
    - assets/audio/color/Pink.mp3
    - assets/audio/color/Purple.mp3
    - assets/audio/color/Red.mp3
    - assets/audio/color/Teal.mp3
    - assets/audio/color/White.mp3
    - assets/audio/color/Yellow.mp3
    #audio animal
    - assets/audio/animal/cat.mp3
    - assets/audio/animal/dog.mp3
    - assets/audio/animal/mouse.mp3
    - assets/audio/animal/lion.mp3
    - assets/audio/animal/giraffe.mp3
    - assets/audio/animal/monkey.mp3
    - assets/audio/animal/parrot.mp3
    - assets/audio/animal/rabbit.mp3
    - assets/audio/animal/turtle.mp3
    - assets/audio/animal/goldfish.mp3
    #audio vehicle
    - assets/audio/vehicle/bicycle.mp3
    - assets/audio/vehicle/bus.mp3
    - assets/audio/vehicle/car.mp3
    - assets/audio/vehicle/cement_truck.mp3
    - assets/audio/vehicle/excavator.mp3
    - assets/audio/vehicle/forklift.mp3
    - assets/audio/vehicle/helicopter.mp3
    - assets/audio/vehicle/plane.mp3
    - assets/audio/vehicle/tank.mp3
    - assets/audio/vehicle/truck.mp3
    - assets/audio/vehicle/motorbike.mp3
    #audio fruits
    - assets/audio/fruits/apple.mp3
    - assets/audio/fruits/apricot.mp3
    - assets/audio/fruits/avocado.mp3
    - assets/audio/fruits/cherry.mp3
    - assets/audio/fruits/coconut.mp3
    - assets/audio/fruits/carrot.mp3
    - assets/audio/fruits/corn.mp3
    - assets/audio/fruits/cucumber.mp3
    - assets/audio/fruits/grape.mp3
    - assets/audio/fruits/grenade.mp3
    - assets/audio/fruits/kiwi.mp3
    - assets/audio/fruits/lemon.mp3
    - assets/audio/fruits/mango.mp3
    - assets/audio/fruits/papaya.mp3
    - assets/audio/fruits/pear.mp3
    - assets/audio/fruits/pineapple.mp3
    - assets/audio/fruits/potato.mp3
    - assets/audio/fruits/tomato.mp3
    - assets/audio/fruits/watermelon.mp3
    - assets/audio/fruits/banana.mp3
    # image background
    - assets/image/background/background.jpg
    - assets/image/background/number.jpg
    - assets/image/background/color.jpg
    - assets/image/background/animal.jpg
    - assets/image/background/fruit.jpg
    - assets/image/background/vehicle.jpg
    - assets/image/background/background_1.jpg
    - assets/image/background/background_2.jpg
    - assets/image/background/background_3.jpg
    # image icon
    - assets/image/icon/playapp.png
    - assets/image/icon/shake.png
    - assets/image/icon/no_shake.png
    # image balloon
    - assets/image/color/balloons.png
    # image animal
    - assets/image/animal/cat.png
    - assets/image/animal/dog.png
    - assets/image/animal/giraffe.png
    - assets/image/animal/lion.png
    - assets/image/animal/monkey.png
    - assets/image/animal/parrot.png
    - assets/image/animal/rabbit.png
    - assets/image/animal/rat.png
    - assets/image/animal/turtle.png
    - assets/image/animal/goldfish.png
    # image vehicle
    - assets/image/vehicle/bicycle.png
    - assets/image/vehicle/bus.png
    - assets/image/vehicle/car.png
    - assets/image/vehicle/delivery-truck.png
    - assets/image/vehicle/excavator.png
    - assets/image/vehicle/forklift.png
    - assets/image/vehicle/helicopter.png
    - assets/image/vehicle/tank.png
    - assets/image/vehicle/truck.png
    - assets/image/vehicle/plane.png
    - assets/image/vehicle/motorbike.png
    # image fruits
    - assets/image/fruits/apple.png
    - assets/image/fruits/apricot.png
    - assets/image/fruits/avocado.png
    - assets/image/fruits/banana.png
    - assets/image/fruits/carrot.png
    - assets/image/fruits/cherry.png
    - assets/image/fruits/coconut.png
    - assets/image/fruits/corn.png
    - assets/image/fruits/cucumber.png
    - assets/image/fruits/grape.png
    - assets/image/fruits/grenade.png
    - assets/image/fruits/kiwi.png
    - assets/image/fruits/lemon.png
    - assets/image/fruits/mango.png
    - assets/image/fruits/papaya.png
    - assets/image/fruits/pear.png
    - assets/image/fruits/pineapple.png
    - assets/image/fruits/potato.png
    - assets/image/fruits/watermelon.png
    - assets/image/fruits/tomato.png





