name: random_number
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.8.2
  path_provider: ^0.5.0+1
  carousel_slider: ^1.0.1
  sensors: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/alphabet/a.mp3
  - assets/alphabet/b.mp3
  - assets/alphabet/c.mp3
  - assets/alphabet/d.mp3
  - assets/alphabet/e.mp3
  - assets/alphabet/f.mp3
  - assets/alphabet/g.mp3
  - assets/alphabet/h.mp3
  - assets/alphabet/i.mp3
  - assets/alphabet/j.mp3
  - assets/alphabet/k.mp3
  - assets/alphabet/l.mp3
  - assets/alphabet/m.mp3
  - assets/alphabet/n.mp3
  - assets/alphabet/o.mp3
  - assets/alphabet/p.mp3
  - assets/alphabet/q.mp3
  - assets/alphabet/r.mp3
  - assets/alphabet/s.mp3
  - assets/alphabet/u.mp3
  - assets/alphabet/v.mp3
  - assets/alphabet/w.mp3
  - assets/alphabet/x.mp3
  - assets/alphabet/y.mp3
  - assets/alphabet/z.mp3
  - assets/alphabet/t.mp3
  - assets/color/Black.mp3
  - assets/color/Blue.mp3
  - assets/color/Brown.mp3
  - assets/color/Green.mp3
  - assets/color/Lime.mp3
  - assets/color/Orange.mp3
  - assets/color/Pink.mp3
  - assets/color/Purple.mp3
  - assets/color/Red.mp3
  - assets/color/Teal.mp3
  - assets/color/White.mp3
  - assets/color/Yellow.mp3
  - assets/animal/cat.mp3
  - assets/animal/dog.mp3
  - assets/animal/mouse.mp3
  - assets/animal/lion.mp3
  - assets/animal/giraffe.mp3
  - assets/animal/monkey.mp3
  - assets/animal/parrot.mp3
  - assets/animal/rabbit.mp3
  - assets/animal/turtle.mp3
  - assets/animal/goldfish.mp3
  - lib/res/images/background.jpg
  - lib/res/images/number.jpg
  - lib/res/images/color.jpg
  - lib/res/images/animal.jpg
  - lib/res/images/fruit.jpg
  - lib/res/images/vehicle.jpg
  - lib/res/images/color_background.jpg
  - lib/res/images/background_1.jpg
  - lib/res/images/background_2.jpg
  - assets/alphabet/0.mp3
  - assets/alphabet/1.mp3
  - assets/alphabet/2.mp3
  - assets/alphabet/3.mp3
  - assets/alphabet/4.mp3
  - assets/alphabet/5.mp3
  - assets/alphabet/6.mp3
  - assets/alphabet/7.mp3
  - assets/alphabet/8.mp3
  - assets/alphabet/9.mp3
  - assets/alphabet/10.mp3
  - lib/res/images/playapp.png
  - lib/res/images/animal/cat.png
  - lib/res/images/animal/dog.png
  - lib/res/images/animal/giraffe.png
  - lib/res/images/animal/lion.png
  - lib/res/images/animal/monkey.png
  - lib/res/images/animal/parrot.png
  - lib/res/images/animal/rabbit.png
  - lib/res/images/animal/rat.png
  - lib/res/images/animal/turtle.png
  - lib/res/images/animal/goldfish.png
  - lib/res/images/vehicle/bicycle.png
  - lib/res/images/vehicle/bus.png
  - lib/res/images/vehicle/car.png
  - lib/res/images/vehicle/delivery-truck.png
  - lib/res/images/vehicle/excavator.png
  - lib/res/images/vehicle/forklift.png
  - lib/res/images/vehicle/helicopter.png
  - lib/res/images/vehicle/tank.png
  - lib/res/images/vehicle/truck.png
  - lib/res/images/vehicle/air-freight.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
