name: random_number
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.8.2
  path_provider: ^0.5.0+1
  sensors: ^0.4.0+1
  after_layout: ^1.0.7
  shimmer: ^1.0.0
  shared_preferences: ^0.5.1+1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #AUDIO ENGLISH
    #audio alphabet
    - assets/audio/english/alphabet/a.mp3
    - assets/audio/english/alphabet/b.mp3
    - assets/audio/english/alphabet/c.mp3
    - assets/audio/english/alphabet/d.mp3
    - assets/audio/english/alphabet/e.mp3
    - assets/audio/english/alphabet/f.mp3
    - assets/audio/english/alphabet/g.mp3
    - assets/audio/english/alphabet/h.mp3
    - assets/audio/english/alphabet/i.mp3
    - assets/audio/english/alphabet/j.mp3
    - assets/audio/english/alphabet/k.mp3
    - assets/audio/english/alphabet/l.mp3
    - assets/audio/english/alphabet/m.mp3
    - assets/audio/english/alphabet/n.mp3
    - assets/audio/english/alphabet/o.mp3
    - assets/audio/english/alphabet/p.mp3
    - assets/audio/english/alphabet/q.mp3
    - assets/audio/english/alphabet/r.mp3
    - assets/audio/english/alphabet/s.mp3
    - assets/audio/english/alphabet/u.mp3
    - assets/audio/english/alphabet/v.mp3
    - assets/audio/english/alphabet/w.mp3
    - assets/audio/english/alphabet/x.mp3
    - assets/audio/english/alphabet/y.mp3
    - assets/audio/english/alphabet/z.mp3
    - assets/audio/english/alphabet/t.mp3
    #audio number
    - assets/audio/english/number/0.mp3
    - assets/audio/english/number/1.mp3
    - assets/audio/english/number/2.mp3
    - assets/audio/english/number/3.mp3
    - assets/audio/english/number/4.mp3
    - assets/audio/english/number/5.mp3
    - assets/audio/english/number/6.mp3
    - assets/audio/english/number/7.mp3
    - assets/audio/english/number/8.mp3
    - assets/audio/english/number/9.mp3

    #audio color
    - assets/audio/english/color/Black.mp3
    - assets/audio/english/color/Blue.mp3
    - assets/audio/english/color/Brown.mp3
    - assets/audio/english/color/Green.mp3
    - assets/audio/english/color/Lime.mp3
    - assets/audio/english/color/Orange.mp3
    - assets/audio/english/color/Pink.mp3
    - assets/audio/english/color/Purple.mp3
    - assets/audio/english/color/Red.mp3
    - assets/audio/english/color/Teal.mp3
    - assets/audio/english/color/White.mp3
    - assets/audio/english/color/Yellow.mp3
    #audio animal
    - assets/audio/english/animal/cat.mp3
    - assets/audio/english/animal/dog.mp3
    - assets/audio/english/animal/mouse.mp3
    - assets/audio/english/animal/lion.mp3
    - assets/audio/english/animal/giraffe.mp3
    - assets/audio/english/animal/monkey.mp3
    - assets/audio/english/animal/parrot.mp3
    - assets/audio/english/animal/rabbit.mp3
    - assets/audio/english/animal/turtle.mp3
    - assets/audio/english/animal/goldfish.mp3
    #audio vehicle
    - assets/audio/english/vehicle/bicycle.mp3
    - assets/audio/english/vehicle/bus.mp3
    - assets/audio/english/vehicle/car.mp3
    - assets/audio/english/vehicle/cement_truck.mp3
    - assets/audio/english/vehicle/excavator.mp3
    - assets/audio/english/vehicle/forklift.mp3
    - assets/audio/english/vehicle/helicopter.mp3
    - assets/audio/english/vehicle/plane.mp3
    - assets/audio/english/vehicle/tank.mp3
    - assets/audio/english/vehicle/truck.mp3
    - assets/audio/english/vehicle/motorbike.mp3
    #audio fruits
    - assets/audio/english/fruits/apple.mp3
    - assets/audio/english/fruits/apricot.mp3
    - assets/audio/english/fruits/avocado.mp3
    - assets/audio/english/fruits/cherry.mp3
    - assets/audio/english/fruits/coconut.mp3
    - assets/audio/english/fruits/carrot.mp3
    - assets/audio/english/fruits/corn.mp3
    - assets/audio/english/fruits/cucumber.mp3
    - assets/audio/english/fruits/grape.mp3
    - assets/audio/english/fruits/grenade.mp3
    - assets/audio/english/fruits/kiwi.mp3
    - assets/audio/english/fruits/lemon.mp3
    - assets/audio/english/fruits/mango.mp3
    - assets/audio/english/fruits/papaya.mp3
    - assets/audio/english/fruits/pear.mp3
    - assets/audio/english/fruits/pineapple.mp3
    - assets/audio/english/fruits/potato.mp3
    - assets/audio/english/fruits/tomato.mp3
    - assets/audio/english/fruits/watermelon.mp3
    - assets/audio/english/fruits/banana.mp3

    #AUDIO VIETNAMESE
    #audio number
    - assets/audio/vietnamese/number/0-vn.mp3
    - assets/audio/vietnamese/number/1-vn.mp3
    - assets/audio/vietnamese/number/2-vn.mp3
    - assets/audio/vietnamese/number/3-vn.mp3
    - assets/audio/vietnamese/number/4-vn.mp3
    - assets/audio/vietnamese/number/5-vn.mp3
    - assets/audio/vietnamese/number/6-vn.mp3
    - assets/audio/vietnamese/number/7-vn.mp3
    - assets/audio/vietnamese/number/8-vn.mp3
    - assets/audio/vietnamese/number/9-vn.mp3

    #audio alphabet
    - assets/audio/vietnamese/alphabet/a-conca.mp3
    - assets/audio/vietnamese/alphabet/aa-caican.mp3
    - assets/audio/vietnamese/alphabet/aw-contran.mp3
    - assets/audio/vietnamese/alphabet/b-conbo.mp3
    - assets/audio/vietnamese/alphabet/c-concua.mp3
    - assets/audio/vietnamese/alphabet/d-conde.mp3
    - assets/audio/vietnamese/alphabet/dd-conduong.mp3
    - assets/audio/vietnamese/alphabet/e-cayme.mp3
    - assets/audio/vietnamese/alphabet/ee-traile.mp3
    - assets/audio/vietnamese/alphabet/g-caygay.mp3
    - assets/audio/vietnamese/alphabet/h-hoahong.mp3
    - assets/audio/vietnamese/alphabet/i-conkhi.mp3
    - assets/audio/vietnamese/alphabet/k-caykhe.mp3
    - assets/audio/vietnamese/alphabet/l-chiecla.mp3
    - assets/audio/vietnamese/alphabet/m-conmeo.mp3
    - assets/audio/vietnamese/alphabet/n-cainoi.mp3
    - assets/audio/vietnamese/alphabet/o-contho.mp3
    - assets/audio/vietnamese/alphabet/oo-caio.mp3
    - assets/audio/vietnamese/alphabet/ow-caino.mp3
    - assets/audio/vietnamese/alphabet/p-caiphin.mp3
    - assets/audio/vietnamese/alphabet/q-caiquan.mp3
    - assets/audio/vietnamese/alphabet/r-carot.mp3
    - assets/audio/vietnamese/alphabet/s-chimse.mp3
    - assets/audio/vietnamese/alphabet/t-batien.mp3
    - assets/audio/vietnamese/alphabet/u-cailu.mp3
    - assets/audio/vietnamese/alphabet/uw-baothu.mp3
    - assets/audio/vietnamese/alphabet/v-conve.mp3
    - assets/audio/vietnamese/alphabet/x-caixeng.mp3
    - assets/audio/vietnamese/alphabet/y-lynuoc.mp3
    #audio color
    - assets/audio/vietnamese/color/cam.mp3
    - assets/audio/vietnamese/color/den.mp3
    - assets/audio/vietnamese/color/do.mp3
    - assets/audio/vietnamese/color/hong.mp3
    - assets/audio/vietnamese/color/nau.mp3
    - assets/audio/vietnamese/color/trang.mp3
    - assets/audio/vietnamese/color/vangchanh.mp3
    - assets/audio/vietnamese/color/xanhduong.mp3
    - assets/audio/vietnamese/color/xanhlacay.mp3
    - assets/audio/vietnamese/color/xanhmongket.mp3
    - assets/audio/vietnamese/color/tim.mp3
    - assets/audio/vietnamese/color/vang.mp3
    #audio animal
    - assets/audio/vietnamese/animal/cavang.mp3
    - assets/audio/vietnamese/animal/concho.mp3
    - assets/audio/vietnamese/animal/conchuot.mp3
    - assets/audio/vietnamese/animal/conkhi.mp3
    - assets/audio/vietnamese/animal/conmeo.mp3
    - assets/audio/vietnamese/animal/conrua.mp3
    - assets/audio/vietnamese/animal/consutu.mp3
    - assets/audio/vietnamese/animal/contho.mp3
    - assets/audio/vietnamese/animal/convet.mp3
    - assets/audio/vietnamese/animal/huoucaoco.mp3
    #audio vehicle
    - assets/audio/vietnamese/vehicle/betong.mp3
    - assets/audio/vietnamese/vehicle/buyt.mp3
    - assets/audio/vietnamese/vehicle/maybay.mp3
    - assets/audio/vietnamese/vehicle/tructhang.mp3
    - assets/audio/vietnamese/vehicle/xecancau.mp3
    - assets/audio/vietnamese/vehicle/xedap.mp3
    - assets/audio/vietnamese/vehicle/xemay.mp3
    - assets/audio/vietnamese/vehicle/xenang.mp3
    - assets/audio/vietnamese/vehicle/xeoto.mp3
    - assets/audio/vietnamese/vehicle/xetai.mp3
    - assets/audio/vietnamese/vehicle/xetang.mp3
    - assets/audio/vietnamese/vehicle/xexucdat.mp3
    #audio fruits
    - assets/audio/vietnamese/fruits/bap.mp3
    - assets/audio/vietnamese/fruits/bo.mp3
    - assets/audio/vietnamese/fruits/cachua.mp3
    - assets/audio/vietnamese/fruits/cam.mp3
    - assets/audio/vietnamese/fruits/carot.mp3
    - assets/audio/vietnamese/fruits/chanh.mp3
    - assets/audio/vietnamese/fruits/cherry-vn.mp3
    - assets/audio/vietnamese/fruits/chuoi.mp3
    - assets/audio/vietnamese/fruits/dua.mp3
    - assets/audio/vietnamese/fruits/dua-thom.mp3
    - assets/audio/vietnamese/fruits/duahau.mp3
    - assets/audio/vietnamese/fruits/dualeo.mp3
    - assets/audio/vietnamese/fruits/dudu.mp3
    - assets/audio/vietnamese/fruits/khoaitay.mp3
    - assets/audio/vietnamese/fruits/kiwi-vn.mp3
    - assets/audio/vietnamese/fruits/le.mp3
    - assets/audio/vietnamese/fruits/luu.mp3
    - assets/audio/vietnamese/fruits/mo.mp3
    - assets/audio/vietnamese/fruits/nho.mp3
    - assets/audio/vietnamese/fruits/tao.mp3
    - assets/audio/vietnamese/fruits/xoai.mp3
    #audio background
    - assets/background_audio/sparrow_audio.mp3



    #IMAGE
    # image background
    - assets/image/background/background.jpg
    - assets/image/background/number.jpg
    - assets/image/background/color.jpg
    - assets/image/background/animal.jpg
    - assets/image/background/fruit.jpg
    - assets/image/background/vehicle.jpg
    - assets/image/background/background_1.jpg
    - assets/image/background/background_2.jpg
    - assets/image/background/background_3.jpg
    - assets/image/background/background_board.jpg
    - assets/image/background/background_wooden.png
    # image icon
    - assets/image/icon/playapp.png
    - assets/image/icon/shake.png
    - assets/image/icon/no_shake.png
    - assets/image/icon/english.png
    - assets/image/icon/vietnamese.png
    - assets/image/icon/french.png
    - assets/image/icon/nextIcon.png
    - assets/image/icon/dove1.png
    - assets/image/icon/dove2.png
    - assets/image/icon/woodsign.png


    # image alphabet
    - assets/image/alphabet/A.png
    - assets/image/alphabet/B.png
    - assets/image/alphabet/C.png
    - assets/image/alphabet/D.png
    - assets/image/alphabet/E.png
    - assets/image/alphabet/F.png
    - assets/image/alphabet/G.png
    - assets/image/alphabet/H.png
    - assets/image/alphabet/I.png
    - assets/image/alphabet/J.png
    - assets/image/alphabet/K.png
    - assets/image/alphabet/L.png
    - assets/image/alphabet/M.png
    - assets/image/alphabet/N.png
    - assets/image/alphabet/O.png
    - assets/image/alphabet/P.png
    - assets/image/alphabet/Q.png
    - assets/image/alphabet/R.png
    - assets/image/alphabet/S.png
    - assets/image/alphabet/T.png
    - assets/image/alphabet/U.png
    - assets/image/alphabet/V.png
    - assets/image/alphabet/W.png
    - assets/image/alphabet/X.png
    - assets/image/alphabet/Y.png
    - assets/image/alphabet/Z.png

    #image alphabet-Vietnamese
    - assets/image/alphabet-vn/A-vn.png
    - assets/image/alphabet-vn/Aa-vn.png
    - assets/image/alphabet-vn/Aw-vn.png
    - assets/image/alphabet-vn/B-vn.png
    - assets/image/alphabet-vn/C-vn.png
    - assets/image/alphabet-vn/D.png
    - assets/image/alphabet-vn/Dd-vn.png
    - assets/image/alphabet-vn/E-vn.png
    - assets/image/alphabet-vn/Ee-vn.png
    - assets/image/alphabet-vn/G-vn.png
    - assets/image/alphabet-vn/H-vn.png
    - assets/image/alphabet-vn/I-vn.png
    - assets/image/alphabet-vn/K-vn.png
    - assets/image/alphabet-vn/L-vn.png
    - assets/image/alphabet-vn/M-vn.png
    - assets/image/alphabet-vn/N-vn.png
    - assets/image/alphabet-vn/O-vn.png
    - assets/image/alphabet-vn/Oo-vn.png
    - assets/image/alphabet-vn/Ow-vn.png
    - assets/image/alphabet-vn/P-vn.png
    - assets/image/alphabet-vn/Q-vn.png
    - assets/image/alphabet-vn/R-vn.png
    - assets/image/alphabet-vn/S-vn.png
    - assets/image/alphabet-vn/T-vn.png
    - assets/image/alphabet-vn/U-vn.png
    - assets/image/alphabet-vn/Uw-vn.png
    - assets/image/alphabet-vn/V-vn.png
    - assets/image/alphabet-vn/X-vn.png
    - assets/image/alphabet-vn/Y-vn.png


    # image number
    - assets/image/number/0.png
    - assets/image/number/1.png
    - assets/image/number/2.png
    - assets/image/number/3.png
    - assets/image/number/4.png
    - assets/image/number/5.png
    - assets/image/number/6.png
    - assets/image/number/7.png
    - assets/image/number/8.png
    - assets/image/number/9.png
    # image balloon
    - assets/image/color/balloons.png
    # image animal
    - assets/image/animal/cat.png
    - assets/image/animal/dog.png
    - assets/image/animal/giraffe.png
    - assets/image/animal/lion.png
    - assets/image/animal/monkey.png
    - assets/image/animal/parrot.png
    - assets/image/animal/rabbit.png
    - assets/image/animal/rat.png
    - assets/image/animal/turtle.png
    - assets/image/animal/goldfish.png
    # image vehicle
    - assets/image/vehicle/bicycle.png
    - assets/image/vehicle/bus.png
    - assets/image/vehicle/car.png
    - assets/image/vehicle/delivery-truck.png
    - assets/image/vehicle/excavator.png
    - assets/image/vehicle/forklift.png
    - assets/image/vehicle/helicopter.png
    - assets/image/vehicle/tank.png
    - assets/image/vehicle/truck.png
    - assets/image/vehicle/plane.png
    - assets/image/vehicle/motorbike.png
    # image fruits
    - assets/image/fruits/apple.png
    - assets/image/fruits/apricot.png
    - assets/image/fruits/avocado.png
    - assets/image/fruits/banana.png
    - assets/image/fruits/carrot.png
    - assets/image/fruits/cherry.png
    - assets/image/fruits/coconut.png
    - assets/image/fruits/corn.png
    - assets/image/fruits/cucumber.png
    - assets/image/fruits/grape.png
    - assets/image/fruits/grenade.png
    - assets/image/fruits/kiwi.png
    - assets/image/fruits/lemon.png
    - assets/image/fruits/mango.png
    - assets/image/fruits/papaya.png
    - assets/image/fruits/pear.png
    - assets/image/fruits/pineapple.png
    - assets/image/fruits/potato.png
    - assets/image/fruits/watermelon.png
    - assets/image/fruits/tomato.png








